### ISSUE TITLE
WiFi Password

### ISSUE THREAD

**Issue by Meth0d007** [JanisEst/KeePassQRCodeView#13]
How do you actually gernerate QR Codes for Android / iOS WiFi Network?
If you use the QR Code from the "Password" field the Images does not work, AFAIK there needs to be a combination of SSID+Pass for this to work.

**Comment by JanisEst** [comment]
I have created a custom string field with the content:

`WIFI:S:{S:WLAN_SSID};T:WPA;P:{S:WLAN_KEY};;`

This references the custom fields `WLAN_SSID` and `WLAN_KEY`. You can reference the default password field if there is the wlan key and use a constant for the ssid:

`WIFI:S:123456;T:WPA;P:{PASSWORD};;`
