### ISSUE TITLE
Save QR as PNG

### ISSUE THREAD

**Issue by vivadavid** [JanisEst/KeePassQRCodeView#14]
Hello,

I was wondering if the QR could be saved as a PNG image. Saving as a JPEG creates some artefacts.

Thanks in advance!

**Comment by vivadavid** [comment]
Hi, I left the comment above a year ago. Any chance it could be implemented? Thanks!

**Comment by JanisEst** [comment]
Sorry, forgot about that. Added in aabf86e4245692c284378a2ab15640124c17f849.

**Comment by vivadavid** [comment]
Thank you, @JanisEst !
