### ISSUE TITLE
AppData\Local\KeePass\PluginCache\ is created using KeePass portable

### ISSUE THREAD

**Issue by AdKiller** [JanisEst/KeePassQRCodeView#15]
When using Keepass portable (zip archive extracted to a USB drive), this file is left on the local drive.

AppData\Local\KeePass\PluginCache\ *random code* \KeePassQRCodeView.dll

What exactly is in the cache?

This could be a big security & privacy risk when you use KeePass portable on an untrustworthy system. 

KeePassQRCodeView 1.0.4.0
KeePass 2.49 64bit
Windows 10 21H2

**Comment by JanisEst** [comment]
KeePass creates this folder for plugins.
https://sourceforge.net/p/keepass/discussion/329221/thread/ca50775e/

**Comment by AdKiller** [comment]
Thanks for the info.
