### ISSUE TITLE
Print/Save Icons in the way

### ISSUE THREAD

**Issue by johnmilleker** [JanisEst/KeePassQRCodeView#16]
Great app, thank you! 

However, on a 4k laptop screen the QR Code is partially hidden behind the print and save buttons. Running KeePass 2.51.1 but these sort of things happen with many plugins because of the 4k screen.

Dragging the window larger separates the icons and the QR Code, but would be great to remember the new window size OR an option to turn off the print and save icons.

**Comment by JanisEst** [comment]
I switched from buttons to a context menu in d306177f88288aeb62eae515dc452c82365c0746.
