### ISSUE TITLE
Resize image or save it into a file?

### ISSUE THREAD

**Issue by Sanyy** [JanisEst/KeePassQRCodeView#3]
Hi,

The shown picture was bigger than the screen.

- can't resize
- can't save into a file to open with something else that can resize or send this picture

thanks,

**Comment by Sanyy** [comment]
like this addon, exactly like this:

https://github.com/catholicon/OfflineQR

**Comment by KN4CK3R** [comment]
Currently only as code. I will release a compiled version tomorrow.
Now the window with the code will not grow larger than the screen. The save button is still missing. I will add it before releasing.

**Comment by KN4CK3R** [comment]
See release v1.0.3

**Comment by Sanyy** [comment]
OS: Windows 7 x64
KeePass: 2.35
Plugin: 1.0.3

![2017-03-23 23_11_28-keepass](https://cloud.githubusercontent.com/assets/17810774/24272637/7352d2fa-101e-11e7-80bd-ac95e8734412.png)
