### ISSUE TITLE
Problem with 1.0.3 version

### ISSUE THREAD

**Issue by Havokdan** [JanisEst/KeePassQRCodeView#4]
![sem titulo](https://cloud.githubusercontent.com/assets/6549729/24287776/c183af68-1059-11e7-80e7-e0f83b11463e.png)

Doenst work in Keepass 2.35 in Windows 10 x64.

**Comment by Xloctis** [comment]
![image](https://cloud.githubusercontent.com/assets/13437936/24296237/1854a00c-10c0-11e7-9bfe-545883111ee5.png)

same problem win 10 x64 Keepass2.35

**Comment by KN4CK3R** [comment]
Fixed the last broken update:
![grafik](https://cloud.githubusercontent.com/assets/1666336/24315693/decad7e2-10e8-11e7-87ff-891959efd8a4.png)
