### ISSUE TITLE
No difference between 1.0.2. vs 1.0.3.1.

### ISSUE THREAD

**Issue by Sanyy** [JanisEst/KeePassQRCodeView#5]
I still can't:
- resize the window
- save the picture -where is the button?-

Can you post an image about this new feature that actually worked for you?

**Comment by KN4CK3R** [comment]
Sorry, something is fishy about the 1.0.3 update :( A resizeable window wasn't planned, just autofit for the used screen. I added the ability to resize the window now.

**Comment by Sanyy** [comment]
Nice job, works fine!

Thanks!
