### ISSUE TITLE
How are qr codes generated?

### ISSUE THREAD

**Issue by ST-DDT** [JanisEst/KeePassQRCodeView#8]
Could you please add a section to your readme how you generate your qrcodes?

* Do you use an (embedded) library to generate them
* or do you an online service to generate them

I'm haunted by (qrCode) plugins for various applications that use some (dubious) web services to generate or render their content. Usually, such an explicit information wouldn't be needed, but this plugin is for a password manager.

**Comment by JanisEst** [comment]
The QR codes are obviously generated without a web service. There are plugins which send sensitive data to a service to generate the code? The code can be found here: https://github.com/JanisEst/KeePassQRCodeView/blob/master/QRCodeGenerator.cs
